name: StickPower
main: MasApip\StickPower\Main
version: 1.0.0
api: [3.0.0, 4.0.0]
commands:
    stickpower:
        default: true
        description: Open Stick Power menu
        permission: stickpower.command
